
<form class="form contact"
      action="<?= $block->escapeUrl($block->getFormAction()) ?>"
      id="contact-form"
      method="post"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <legend class="legend"><span><?= $block->escapeHtml(__('Write Us')) ?></span></legend><br />
		<div class="field name required">
            <label class="label" for="name"><span><?= $block->escapeHtml(__('Firstname')) ?></span></label>
            <div class="control">
                <input name="firstname"
                       id="firstname"
                       title="<?= $block->escapeHtmlAttr(__('First Name')) ?>"
                       class="input-text"
                       type="text"
                       data-validate="{required:true}"/>

            </div>
        </div>
        <div class="field name">
            <label class="label" for="name"><span><?= $block->escapeHtml(__('Lastname')) ?></span></label>
            <div class="control">
                <input name="lastname"
                       id="lastname"
                       title="<?= $block->escapeHtmlAttr(__('Last Name')) ?>"
                       class="input-text"
                       type="text"/>
            </div>
        </div>
        <div class="field email required">
            <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
            <div class="control">
                <input name="email"
                       id="email"
                       title="<?= $block->escapeHtmlAttr(__('Email')) ?>"
                       class="input-text"
                       type="email"
                       data-validate="{required:true, 'validate-email':true}"/>
            </div>
        </div>
        <div class="field gender">
            <label class="label" for="gender"><span><?= $block->escapeHtml(__('Gender')) ?></span></label>
            <div class="control">
                <select class="input-text" id="gender" name="gender" >
                    <option>Select Gender</option>
                    <option Value="Male">Male</option>
                    <option Value="Female">Female</option>
                </select>
            </div>
        </div>
        <div class="field phone">
            <label class="label" for="Phone"><span><?= $block->escapeHtml(__('Phone Number')) ?></span></label>
            <div class="control">
                <input name="phone"
                       id="phone"
                       title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>"
                       class="input-text"
                       type="tel" />
            </div>
        </div>
        <div class="field comment required">
            <label class="label" for="comment">
                <span><?= $block->escapeHtml(__('What’s on your mind?')) ?></span>
            </label>
            <div class="control">
                <textarea name="comment"
                     id="comment"
                     title="<?= $block->escapeHtmlAttr(__('What’s on your mind?')) ?>"
                     class="input-text"
                     cols="5"
                     rows="3"
                     data-validate="{required:true}"></textarea>
            </div>
        </div>
        <?= $block->getChildHtml('form.additional.info') ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button type="submit" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>" class="action submit primary">
                <span><?= $block->escapeHtml(__('Submit')) ?></span>
            </button>
        </div>
    </div>
</form>
